# -*- coding: utf-8 -*-
"""DB_SCAN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WJSMDz9loYQMvg7_C6R3TnBKRYqj5nqR
"""

import pandas as pd
import numpy as np
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

df=pd.read_csv('https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/Mall_Customers.csv')
df.head()

features=['Annual Income (k$)','Spending Score (1-100)']
x=df[features]

x_standardized =StandardScaler().fit_transform(x)

dbscan = DBSCAN(eps=0.5, min_samples=5)
clusters = dbscan.fit_predict(x_standardized)
clusters

centroids=pd.DataFrame(x_standardized).groupby(clusters).mean().values

plt.figure(figsize=(8, 6))
plt.scatter(x['Annual Income (k$)'], x['Spending Score (1-100)'], c=clusters, cmap='viridis', edgecolors='k', s=50)
plt.title('DBSCAN Clustering of Mall Customer Data')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.show()