# -*- coding: utf-8 -*-
"""dbscan_IRIS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xm9SXA0YCN_J-03kxAObfMmZ0j92V6oo
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv('/Iris.csv')

df.head()

df.info()

df.describe()

df.shape

df.isnull().sum()

from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler

features=['SepalLengthCm','PetalLengthCm']
x=df[features]

x_standardized =StandardScaler().fit_transform(x)

dbscan = DBSCAN(eps=0.5, min_samples=5)
clusters = dbscan.fit_predict(x_standardized)
clusters

centroids=pd.DataFrame(x_standardized).groupby(clusters).mean().values

plt.figure(figsize=(8, 6))
plt.scatter(x['SepalLengthCm'], x['PetalLengthCm'], c=clusters, cmap='viridis', edgecolors='k', s=50)
plt.title('DBSCAN Clustering of IRIS dataset')
plt.xlabel('SepalLengthCm')
plt.ylabel('PetalLengthCm')
plt.show()

