# -*- coding: utf-8 -*-
"""k_MEANS_mall_customer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LFjkDTDaAPWIySTJgMqyoHEoKggtSV4v
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import plotly as py
import plotly.graph_objs as go

from sklearn.cluster import KMeans

import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv('https://raw.githubusercontent.com/ezioauditore-tech/AI/main/datasets/Mall_Customers.csv')

df.head()

df.shape

df.info()

df.describe()

df.isnull().sum()

x=df.iloc[:,[3,4]].values
x

from sklearn.cluster import KMeans
cen=[]

for i in range(1,11):
  kmeans=KMeans(n_clusters=i,init='k-means++',random_state=0)
  kmeans.fit(x)
  cen.append(kmeans.inertia_)

plt.plot(range(1,11),cen)

plt.title('k means')
plt.xlabel('x axis')
plt.ylabel('y axis')
plt.legend()
plt.show()

