# -*- coding: utf-8 -*-
"""L1,L2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/102arGBgOXu__JxVZU9Qq49SOS319gSnR
"""

import numpy as np
import matplotlib.pyplot as plt

x=np.array([1,2,3,4,5])
y=np.array([2.1,3.8,6.5,9.2,11.3])

x_b=np.c_[np.ones((x.shape[0],1)),x]
x_b

alpha_ridge=1.0
alpha_lasso=0.1
num_iteration=1000
learning_rate=0.001

def lasso_regression(x,y,aplha,num_iteration,learning_rate):
  m,n=x.shape
  theta=np.zeros(n)
  for _ in range(num_iteration):
    y_pred=x.dot(theta)
    gradient=(x.T.dot(y_pred-y)+aplha*np.sign(theta))
    theta -=learning_rate * gradient
  return theta

def ridge_regression(x,y,aplha,num_iteration,learning_rate):
  m,n=x.shape
  theta=np.zeros(n)
  for _ in range(num_iteration):
    y_pred=x.dot(theta)
    gradient=(x.T.dot(y_pred-y)+aplha*theta)/n
    theta -=learning_rate * gradient
  return theta

theta_ridge=ridge_regression(x_b,y,alpha_ridge,num_iteration,learning_rate)
theta_lasso=lasso_regression(x_b,y,alpha_lasso,num_iteration,learning_rate)

plt.scatter(x,y,label='Data')
plt.plot(x,x_b.dot(theta_ridge),label=f'Ridge (L2) Regression',color='r')
plt.plot(x,x_b.dot(theta_lasso),label=f'Lasso (L1) Regression',color='g')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.show()

